export const imageToolText = {
  "en": {
    "imageToolsTitle": "Image Tools",
    "imageToolsDesc": "Compress, rotate and convert images privately in your browser.",
    "open": "Open Tool",
    "compressTitle": "Compress & Rotate Image",
    "compressDesc": "Reduce image file size and rotate your image before download.",
    "convertTitle": "JPG to PNG Converter",
    "convertDesc": "Convert JPG images to PNG directly in your browser.",
    "choose": "Choose Image",
    "noImage": "No image selected",
    "download": "Download",
    "preview": "Preview",
    "privacy": "Your image is processed locally in your browser. We do not upload or store your files.",
    "quality": "Quality",
    "downloadCompressed": "Download Image",
    "originalSize": "Original size",
    "newSize": "Estimated new size",
    "actualNewSize": "Downloaded size",
    "rotateLeft": "Rotate Left",
    "rotateRight": "Rotate Right",
    "rotation": "Rotation",
    "convert": "Convert to PNG",
    "downloadPng": "Download PNG",
    "fast": "Fast",
    "secure": "Secure",
    "free": "Free",
    "mobile": "Mobile Friendly",
    "homeTitle": "Free Online Tools",
    "homeDesc": "Choose PDF tools or image tools. Files stay private in your browser.",
    "pdfCategory": "PDF Tools",
    "imageCategory": "Image Tools",
    "pdfDesc": "Convert images to PDF and merge PDF files securely in your browser.",
    "pdfTitle": "PDF Tools"
  },
  "ru": {
    "imageToolsTitle": "Инструменты для изображений",
    "imageToolsDesc": "Сжимайте, поворачивайте и конвертируйте изображения приватно в браузере.",
    "open": "Открыть инструмент",
    "compressTitle": "Сжать и повернуть изображение",
    "compressDesc": "Уменьшите размер файла и поверните изображение перед скачиванием.",
    "convertTitle": "Конвертер JPG в PNG",
    "convertDesc": "Конвертируйте JPG в PNG прямо в браузере.",
    "choose": "Выбрать изображение",
    "noImage": "Изображение не выбрано",
    "download": "Скачать",
    "preview": "Предпросмотр",
    "privacy": "Ваше изображение обрабатывается локально в браузере. Мы не загружаем и не храним файлы.",
    "quality": "Качество",
    "downloadCompressed": "Скачать изображение",
    "originalSize": "Исходный размер",
    "newSize": "Ожидаемый новый размер",
    "actualNewSize": "Размер скачанного файла",
    "rotateLeft": "Повернуть влево",
    "rotateRight": "Повернуть вправо",
    "rotation": "Поворот",
    "convert": "Конвертировать в PNG",
    "downloadPng": "Скачать PNG",
    "fast": "Быстро",
    "secure": "Безопасно",
    "free": "Бесплатно",
    "mobile": "Для телефона",
    "homeTitle": "Бесплатные онлайн-инструменты",
    "homeDesc": "Выберите PDF-инструменты или инструменты для изображений. Файлы остаются приватными в браузере.",
    "pdfCategory": "PDF Инструменты",
    "imageCategory": "Инструменты для изображений",
    "pdfDesc": "Конвертируйте изображения в PDF и объединяйте PDF безопасно в браузере.",
    "pdfTitle": "PDF Инструменты"
  },
  "hi": {
    "imageToolsTitle": "इमेज टूल्स",
    "imageToolsDesc": "इमेज को ब्राउज़र में ही compress, rotate और convert करें।",
    "open": "टूल खोलें",
    "compressTitle": "इमेज Compress और Rotate करें",
    "compressDesc": "Download से पहले image size कम करें और rotate करें।",
    "convertTitle": "JPG से PNG कन्वर्टर",
    "convertDesc": "JPG image को सीधे browser में PNG बनाएं।",
    "choose": "इमेज चुनें",
    "noImage": "कोई इमेज चुनी नहीं गई",
    "download": "डाउनलोड",
    "preview": "प्रीव्यू",
    "privacy": "आपकी इमेज आपके browser में ही process होती है। हम file upload या store नहीं करते।",
    "quality": "क्वालिटी",
    "downloadCompressed": "इमेज डाउनलोड करें",
    "originalSize": "Original size",
    "newSize": "Estimated new size",
    "actualNewSize": "Downloaded size",
    "rotateLeft": "बाएं घुमाएं",
    "rotateRight": "दाएं घुमाएं",
    "rotation": "Rotation",
    "convert": "PNG में बदलें",
    "downloadPng": "PNG डाउनलोड करें",
    "fast": "तेज़",
    "secure": "सुरक्षित",
    "free": "मुफ्त",
    "mobile": "Mobile Friendly",
    "homeTitle": "मुफ्त ऑनलाइन टूल्स",
    "homeDesc": "PDF tools या image tools चुनें। Files आपके browser में private रहती हैं।",
    "pdfCategory": "PDF टूल्स",
    "imageCategory": "इमेज टूल्स",
    "pdfDesc": "इमेज को PDF में बदलें और PDF files को browser में safely merge करें।",
    "pdfTitle": "PDF टूल्स"
  },
  "ar": {
    "imageToolsTitle": "أدوات الصور",
    "imageToolsDesc": "اضغط الصور ودوّرها وحوّلها داخل المتصفح بخصوصية.",
    "open": "افتح الأداة",
    "compressTitle": "ضغط وتدوير الصورة",
    "compressDesc": "قلّل حجم الصورة ودوّرها قبل التنزيل.",
    "convertTitle": "تحويل JPG إلى PNG",
    "convertDesc": "حوّل صور JPG إلى PNG داخل المتصفح.",
    "choose": "اختر صورة",
    "noImage": "لم يتم اختيار صورة",
    "download": "تنزيل",
    "preview": "معاينة",
    "privacy": "تتم معالجة صورتك محلياً داخل المتصفح. لا نرفع أو نخزن ملفاتك.",
    "quality": "الجودة",
    "downloadCompressed": "تنزيل الصورة",
    "originalSize": "الحجم الأصلي",
    "newSize": "الحجم الجديد المتوقع",
    "actualNewSize": "حجم التنزيل",
    "rotateLeft": "تدوير لليسار",
    "rotateRight": "تدوير لليمين",
    "rotation": "الدوران",
    "convert": "تحويل إلى PNG",
    "downloadPng": "تنزيل PNG",
    "fast": "سريع",
    "secure": "آمن",
    "free": "مجاني",
    "mobile": "مناسب للجوال",
    "homeTitle": "أدوات مجانية على الإنترنت",
    "homeDesc": "اختر أدوات PDF أو الصور. تبقى ملفاتك خاصة في المتصفح.",
    "pdfCategory": "أدوات PDF",
    "imageCategory": "أدوات الصور",
    "pdfDesc": "حوّل الصور إلى PDF وادمج ملفات PDF بأمان في المتصفح.",
    "pdfTitle": "أدوات PDF"
  },
  "es": {
    "imageToolsTitle": "Herramientas de imagen",
    "imageToolsDesc": "Comprime, gira y convierte imágenes de forma privada en tu navegador.",
    "open": "Abrir herramienta",
    "compressTitle": "Comprimir y girar imagen",
    "compressDesc": "Reduce el tamaño y gira tu imagen antes de descargar.",
    "convertTitle": "Convertidor JPG a PNG",
    "convertDesc": "Convierte JPG a PNG directamente en tu navegador.",
    "choose": "Elegir imagen",
    "noImage": "No hay imagen seleccionada",
    "download": "Descargar",
    "preview": "Vista previa",
    "privacy": "Tu imagen se procesa localmente en tu navegador. No subimos ni guardamos tus archivos.",
    "quality": "Calidad",
    "downloadCompressed": "Descargar imagen",
    "originalSize": "Tamaño original",
    "newSize": "Nuevo tamaño estimado",
    "actualNewSize": "Tamaño descargado",
    "rotateLeft": "Girar izquierda",
    "rotateRight": "Girar derecha",
    "rotation": "Rotación",
    "convert": "Convertir a PNG",
    "downloadPng": "Descargar PNG",
    "fast": "Rápido",
    "secure": "Seguro",
    "free": "Gratis",
    "mobile": "Móvil",
    "homeTitle": "Herramientas gratis online",
    "homeDesc": "Elige herramientas PDF o de imagen. Tus archivos quedan privados en el navegador.",
    "pdfCategory": "Herramientas PDF",
    "imageCategory": "Herramientas de imagen",
    "pdfDesc": "Convierte imágenes a PDF y une PDFs de forma segura en tu navegador.",
    "pdfTitle": "Herramientas PDF"
  },
  "zh-CN": {
    "imageToolsTitle": "图片工具",
    "imageToolsDesc": "在浏览器中私密压缩、旋转和转换图片。",
    "open": "打开工具",
    "compressTitle": "压缩并旋转图片",
    "compressDesc": "下载前减小图片大小并旋转图片。",
    "convertTitle": "JPG 转 PNG",
    "convertDesc": "直接在浏览器中将 JPG 转为 PNG。",
    "choose": "选择图片",
    "noImage": "未选择图片",
    "download": "下载",
    "preview": "预览",
    "privacy": "图片只在浏览器中本地处理。我们不会上传或存储文件。",
    "quality": "质量",
    "downloadCompressed": "下载图片",
    "originalSize": "原始大小",
    "newSize": "预计新大小",
    "actualNewSize": "下载大小",
    "rotateLeft": "向左旋转",
    "rotateRight": "向右旋转",
    "rotation": "旋转",
    "convert": "转换为 PNG",
    "downloadPng": "下载 PNG",
    "fast": "快速",
    "secure": "安全",
    "free": "免费",
    "mobile": "适合手机",
    "homeTitle": "免费在线工具",
    "homeDesc": "选择 PDF 工具或图片工具。文件保留在浏览器中。",
    "pdfCategory": "PDF 工具",
    "imageCategory": "图片工具",
    "pdfDesc": "在浏览器中安全地将图片转为 PDF 并合并 PDF。",
    "pdfTitle": "PDF 工具"
  },
  "pt": {
    "imageToolsTitle": "Ferramentas de imagem",
    "imageToolsDesc": "Ferramentas de imagem: compress, rotate and convert images privately in your browser.",
    "open": "Abrir ferramenta",
    "compressTitle": "Comprimir e girar imagem",
    "compressDesc": "Reduce image file size and rotate before download.",
    "convertTitle": "Conversor JPG para PNG",
    "convertDesc": "Convert JPG images to PNG directly in your browser.",
    "choose": "Ferramentas de imagem",
    "noImage": "No image selected",
    "download": "Baixar",
    "preview": "Preview",
    "privacy": "Your image is processed locally in your browser. We do not upload or store your files.",
    "quality": "Quality",
    "downloadCompressed": "Baixar",
    "originalSize": "Original size",
    "newSize": "Estimated new size",
    "actualNewSize": "Downloaded size",
    "rotateLeft": "Rotate Left",
    "rotateRight": "Rotate Right",
    "rotation": "Rotation",
    "convert": "Convert to PNG",
    "downloadPng": "Baixar",
    "fast": "Fast",
    "secure": "Secure",
    "free": "Free",
    "mobile": "Mobile Friendly",
    "homeTitle": "Ferramentas online gratuitas",
    "homeDesc": "Choose PDF tools or image tools. Files stay private in your browser.",
    "pdfCategory": "Ferramentas PDF",
    "imageCategory": "Ferramentas de imagem",
    "pdfDesc": "Convert images to PDF and merge PDF files securely in your browser.",
    "pdfTitle": "Ferramentas PDF"
  },
  "fr": {
    "imageToolsTitle": "Outils d’image",
    "imageToolsDesc": "Outils d’image: compress, rotate and convert images privately in your browser.",
    "open": "Ouvrir l’outil",
    "compressTitle": "Compresser et faire pivoter l’image",
    "compressDesc": "Reduce image file size and rotate before download.",
    "convertTitle": "Convertisseur JPG en PNG",
    "convertDesc": "Convert JPG images to PNG directly in your browser.",
    "choose": "Outils d’image",
    "noImage": "No image selected",
    "download": "Télécharger",
    "preview": "Preview",
    "privacy": "Your image is processed locally in your browser. We do not upload or store your files.",
    "quality": "Quality",
    "downloadCompressed": "Télécharger",
    "originalSize": "Original size",
    "newSize": "Estimated new size",
    "actualNewSize": "Downloaded size",
    "rotateLeft": "Rotate Left",
    "rotateRight": "Rotate Right",
    "rotation": "Rotation",
    "convert": "Convert to PNG",
    "downloadPng": "Télécharger",
    "fast": "Fast",
    "secure": "Secure",
    "free": "Free",
    "mobile": "Mobile Friendly",
    "homeTitle": "Outils en ligne gratuits",
    "homeDesc": "Choose PDF tools or image tools. Files stay private in your browser.",
    "pdfCategory": "Outils PDF",
    "imageCategory": "Outils d’image",
    "pdfDesc": "Convert images to PDF and merge PDF files securely in your browser.",
    "pdfTitle": "Outils PDF"
  },
  "de": {
    "imageToolsTitle": "Bild-Tools",
    "imageToolsDesc": "Bild-Tools: compress, rotate and convert images privately in your browser.",
    "open": "Tool öffnen",
    "compressTitle": "Bild komprimieren und drehen",
    "compressDesc": "Reduce image file size and rotate before download.",
    "convertTitle": "JPG zu PNG Konverter",
    "convertDesc": "Convert JPG images to PNG directly in your browser.",
    "choose": "Bild-Tools",
    "noImage": "No image selected",
    "download": "Herunterladen",
    "preview": "Preview",
    "privacy": "Your image is processed locally in your browser. We do not upload or store your files.",
    "quality": "Quality",
    "downloadCompressed": "Herunterladen",
    "originalSize": "Original size",
    "newSize": "Estimated new size",
    "actualNewSize": "Downloaded size",
    "rotateLeft": "Rotate Left",
    "rotateRight": "Rotate Right",
    "rotation": "Rotation",
    "convert": "Convert to PNG",
    "downloadPng": "Herunterladen",
    "fast": "Fast",
    "secure": "Secure",
    "free": "Free",
    "mobile": "Mobile Friendly",
    "homeTitle": "Kostenlose Online-Tools",
    "homeDesc": "Choose PDF tools or image tools. Files stay private in your browser.",
    "pdfCategory": "PDF-Tools",
    "imageCategory": "Bild-Tools",
    "pdfDesc": "Convert images to PDF and merge PDF files securely in your browser.",
    "pdfTitle": "PDF-Tools"
  },
  "ja": {
    "imageToolsTitle": "画像ツール",
    "imageToolsDesc": "画像ツール: compress, rotate and convert images privately in your browser.",
    "open": "ツールを開く",
    "compressTitle": "画像を圧縮・回転",
    "compressDesc": "Reduce image file size and rotate before download.",
    "convertTitle": "JPG から PNG 変換",
    "convertDesc": "Convert JPG images to PNG directly in your browser.",
    "choose": "画像ツール",
    "noImage": "No image selected",
    "download": "ダウンロード",
    "preview": "Preview",
    "privacy": "Your image is processed locally in your browser. We do not upload or store your files.",
    "quality": "Quality",
    "downloadCompressed": "ダウンロード",
    "originalSize": "Original size",
    "newSize": "Estimated new size",
    "actualNewSize": "Downloaded size",
    "rotateLeft": "Rotate Left",
    "rotateRight": "Rotate Right",
    "rotation": "Rotation",
    "convert": "Convert to PNG",
    "downloadPng": "ダウンロード",
    "fast": "Fast",
    "secure": "Secure",
    "free": "Free",
    "mobile": "Mobile Friendly",
    "homeTitle": "無料オンラインツール",
    "homeDesc": "Choose PDF tools or image tools. Files stay private in your browser.",
    "pdfCategory": "PDF ツール",
    "imageCategory": "画像ツール",
    "pdfDesc": "Convert images to PDF and merge PDF files securely in your browser.",
    "pdfTitle": "PDF ツール"
  },
  "id": {
    "imageToolsTitle": "Alat Gambar",
    "imageToolsDesc": "Alat Gambar: compress, rotate and convert images privately in your browser.",
    "open": "Buka Alat",
    "compressTitle": "Kompres & Putar Gambar",
    "compressDesc": "Reduce image file size and rotate before download.",
    "convertTitle": "Konverter JPG ke PNG",
    "convertDesc": "Convert JPG images to PNG directly in your browser.",
    "choose": "Alat Gambar",
    "noImage": "No image selected",
    "download": "Unduh",
    "preview": "Preview",
    "privacy": "Your image is processed locally in your browser. We do not upload or store your files.",
    "quality": "Quality",
    "downloadCompressed": "Unduh",
    "originalSize": "Original size",
    "newSize": "Estimated new size",
    "actualNewSize": "Downloaded size",
    "rotateLeft": "Rotate Left",
    "rotateRight": "Rotate Right",
    "rotation": "Rotation",
    "convert": "Convert to PNG",
    "downloadPng": "Unduh",
    "fast": "Fast",
    "secure": "Secure",
    "free": "Free",
    "mobile": "Mobile Friendly",
    "homeTitle": "Alat Online Gratis",
    "homeDesc": "Choose PDF tools or image tools. Files stay private in your browser.",
    "pdfCategory": "Alat PDF",
    "imageCategory": "Alat Gambar",
    "pdfDesc": "Convert images to PDF and merge PDF files securely in your browser.",
    "pdfTitle": "Alat PDF"
  },
  "tr": {
    "imageToolsTitle": "Görsel Araçları",
    "imageToolsDesc": "Görsel Araçları: compress, rotate and convert images privately in your browser.",
    "open": "Aracı Aç",
    "compressTitle": "Görseli Sıkıştır ve Döndür",
    "compressDesc": "Reduce image file size and rotate before download.",
    "convertTitle": "JPG’den PNG’ye Dönüştürücü",
    "convertDesc": "Convert JPG images to PNG directly in your browser.",
    "choose": "Görsel Araçları",
    "noImage": "No image selected",
    "download": "İndir",
    "preview": "Preview",
    "privacy": "Your image is processed locally in your browser. We do not upload or store your files.",
    "quality": "Quality",
    "downloadCompressed": "İndir",
    "originalSize": "Original size",
    "newSize": "Estimated new size",
    "actualNewSize": "Downloaded size",
    "rotateLeft": "Rotate Left",
    "rotateRight": "Rotate Right",
    "rotation": "Rotation",
    "convert": "Convert to PNG",
    "downloadPng": "İndir",
    "fast": "Fast",
    "secure": "Secure",
    "free": "Free",
    "mobile": "Mobile Friendly",
    "homeTitle": "Ücretsiz Online Araçlar",
    "homeDesc": "Choose PDF tools or image tools. Files stay private in your browser.",
    "pdfCategory": "PDF Araçları",
    "imageCategory": "Görsel Araçları",
    "pdfDesc": "Convert images to PDF and merge PDF files securely in your browser.",
    "pdfTitle": "PDF Araçları"
  },
  "ko": {
    "imageToolsTitle": "이미지 도구",
    "imageToolsDesc": "이미지 도구: compress, rotate and convert images privately in your browser.",
    "open": "도구 열기",
    "compressTitle": "이미지 압축 및 회전",
    "compressDesc": "Reduce image file size and rotate before download.",
    "convertTitle": "JPG를 PNG로 변환",
    "convertDesc": "Convert JPG images to PNG directly in your browser.",
    "choose": "이미지 도구",
    "noImage": "No image selected",
    "download": "다운로드",
    "preview": "Preview",
    "privacy": "Your image is processed locally in your browser. We do not upload or store your files.",
    "quality": "Quality",
    "downloadCompressed": "다운로드",
    "originalSize": "Original size",
    "newSize": "Estimated new size",
    "actualNewSize": "Downloaded size",
    "rotateLeft": "Rotate Left",
    "rotateRight": "Rotate Right",
    "rotation": "Rotation",
    "convert": "Convert to PNG",
    "downloadPng": "다운로드",
    "fast": "Fast",
    "secure": "Secure",
    "free": "Free",
    "mobile": "Mobile Friendly",
    "homeTitle": "무료 온라인 도구",
    "homeDesc": "Choose PDF tools or image tools. Files stay private in your browser.",
    "pdfCategory": "PDF 도구",
    "imageCategory": "이미지 도구",
    "pdfDesc": "Convert images to PDF and merge PDF files securely in your browser.",
    "pdfTitle": "PDF 도구"
  },
  "it": {
    "imageToolsTitle": "Strumenti immagine",
    "imageToolsDesc": "Strumenti immagine: compress, rotate and convert images privately in your browser.",
    "open": "Apri strumento",
    "compressTitle": "Comprimi e ruota immagine",
    "compressDesc": "Reduce image file size and rotate before download.",
    "convertTitle": "Convertitore JPG in PNG",
    "convertDesc": "Convert JPG images to PNG directly in your browser.",
    "choose": "Strumenti immagine",
    "noImage": "No image selected",
    "download": "Scarica",
    "preview": "Preview",
    "privacy": "Your image is processed locally in your browser. We do not upload or store your files.",
    "quality": "Quality",
    "downloadCompressed": "Scarica",
    "originalSize": "Original size",
    "newSize": "Estimated new size",
    "actualNewSize": "Downloaded size",
    "rotateLeft": "Rotate Left",
    "rotateRight": "Rotate Right",
    "rotation": "Rotation",
    "convert": "Convert to PNG",
    "downloadPng": "Scarica",
    "fast": "Fast",
    "secure": "Secure",
    "free": "Free",
    "mobile": "Mobile Friendly",
    "homeTitle": "Strumenti online gratuiti",
    "homeDesc": "Choose PDF tools or image tools. Files stay private in your browser.",
    "pdfCategory": "Strumenti PDF",
    "imageCategory": "Strumenti immagine",
    "pdfDesc": "Convert images to PDF and merge PDF files securely in your browser.",
    "pdfTitle": "Strumenti PDF"
  },
  "nl": {
    "imageToolsTitle": "Afbeeldingstools",
    "imageToolsDesc": "Afbeeldingstools: compress, rotate and convert images privately in your browser.",
    "open": "Tool openen",
    "compressTitle": "Afbeelding comprimeren en draaien",
    "compressDesc": "Reduce image file size and rotate before download.",
    "convertTitle": "JPG naar PNG converter",
    "convertDesc": "Convert JPG images to PNG directly in your browser.",
    "choose": "Afbeeldingstools",
    "noImage": "No image selected",
    "download": "Downloaden",
    "preview": "Preview",
    "privacy": "Your image is processed locally in your browser. We do not upload or store your files.",
    "quality": "Quality",
    "downloadCompressed": "Downloaden",
    "originalSize": "Original size",
    "newSize": "Estimated new size",
    "actualNewSize": "Downloaded size",
    "rotateLeft": "Rotate Left",
    "rotateRight": "Rotate Right",
    "rotation": "Rotation",
    "convert": "Convert to PNG",
    "downloadPng": "Downloaden",
    "fast": "Fast",
    "secure": "Secure",
    "free": "Free",
    "mobile": "Mobile Friendly",
    "homeTitle": "Gratis online tools",
    "homeDesc": "Choose PDF tools or image tools. Files stay private in your browser.",
    "pdfCategory": "PDF-tools",
    "imageCategory": "Afbeeldingstools",
    "pdfDesc": "Convert images to PDF and merge PDF files securely in your browser.",
    "pdfTitle": "PDF-tools"
  },
  "pl": {
    "imageToolsTitle": "Narzędzia obrazów",
    "imageToolsDesc": "Narzędzia obrazów: compress, rotate and convert images privately in your browser.",
    "open": "Otwórz narzędzie",
    "compressTitle": "Kompresuj i obróć obraz",
    "compressDesc": "Reduce image file size and rotate before download.",
    "convertTitle": "Konwerter JPG na PNG",
    "convertDesc": "Convert JPG images to PNG directly in your browser.",
    "choose": "Narzędzia obrazów",
    "noImage": "No image selected",
    "download": "Pobierz",
    "preview": "Preview",
    "privacy": "Your image is processed locally in your browser. We do not upload or store your files.",
    "quality": "Quality",
    "downloadCompressed": "Pobierz",
    "originalSize": "Original size",
    "newSize": "Estimated new size",
    "actualNewSize": "Downloaded size",
    "rotateLeft": "Rotate Left",
    "rotateRight": "Rotate Right",
    "rotation": "Rotation",
    "convert": "Convert to PNG",
    "downloadPng": "Pobierz",
    "fast": "Fast",
    "secure": "Secure",
    "free": "Free",
    "mobile": "Mobile Friendly",
    "homeTitle": "Darmowe narzędzia online",
    "homeDesc": "Choose PDF tools or image tools. Files stay private in your browser.",
    "pdfCategory": "Narzędzia PDF",
    "imageCategory": "Narzędzia obrazów",
    "pdfDesc": "Convert images to PDF and merge PDF files securely in your browser.",
    "pdfTitle": "Narzędzia PDF"
  },
  "th": {
    "imageToolsTitle": "เครื่องมือรูปภาพ",
    "imageToolsDesc": "เครื่องมือรูปภาพ: compress, rotate and convert images privately in your browser.",
    "open": "เปิดเครื่องมือ",
    "compressTitle": "บีบอัดและหมุนรูปภาพ",
    "compressDesc": "Reduce image file size and rotate before download.",
    "convertTitle": "แปลง JPG เป็น PNG",
    "convertDesc": "Convert JPG images to PNG directly in your browser.",
    "choose": "เครื่องมือรูปภาพ",
    "noImage": "No image selected",
    "download": "ดาวน์โหลด",
    "preview": "Preview",
    "privacy": "Your image is processed locally in your browser. We do not upload or store your files.",
    "quality": "Quality",
    "downloadCompressed": "ดาวน์โหลด",
    "originalSize": "Original size",
    "newSize": "Estimated new size",
    "actualNewSize": "Downloaded size",
    "rotateLeft": "Rotate Left",
    "rotateRight": "Rotate Right",
    "rotation": "Rotation",
    "convert": "Convert to PNG",
    "downloadPng": "ดาวน์โหลด",
    "fast": "Fast",
    "secure": "Secure",
    "free": "Free",
    "mobile": "Mobile Friendly",
    "homeTitle": "เครื่องมือออนไลน์ฟรี",
    "homeDesc": "Choose PDF tools or image tools. Files stay private in your browser.",
    "pdfCategory": "เครื่องมือ PDF",
    "imageCategory": "เครื่องมือรูปภาพ",
    "pdfDesc": "Convert images to PDF and merge PDF files securely in your browser.",
    "pdfTitle": "เครื่องมือ PDF"
  },
  "vi": {
    "imageToolsTitle": "Công cụ hình ảnh",
    "imageToolsDesc": "Công cụ hình ảnh: compress, rotate and convert images privately in your browser.",
    "open": "Mở công cụ",
    "compressTitle": "Nén và xoay ảnh",
    "compressDesc": "Reduce image file size and rotate before download.",
    "convertTitle": "Chuyển JPG sang PNG",
    "convertDesc": "Convert JPG images to PNG directly in your browser.",
    "choose": "Công cụ hình ảnh",
    "noImage": "No image selected",
    "download": "Tải xuống",
    "preview": "Preview",
    "privacy": "Your image is processed locally in your browser. We do not upload or store your files.",
    "quality": "Quality",
    "downloadCompressed": "Tải xuống",
    "originalSize": "Original size",
    "newSize": "Estimated new size",
    "actualNewSize": "Downloaded size",
    "rotateLeft": "Rotate Left",
    "rotateRight": "Rotate Right",
    "rotation": "Rotation",
    "convert": "Convert to PNG",
    "downloadPng": "Tải xuống",
    "fast": "Fast",
    "secure": "Secure",
    "free": "Free",
    "mobile": "Mobile Friendly",
    "homeTitle": "Công cụ online miễn phí",
    "homeDesc": "Choose PDF tools or image tools. Files stay private in your browser.",
    "pdfCategory": "Công cụ PDF",
    "imageCategory": "Công cụ hình ảnh",
    "pdfDesc": "Convert images to PDF and merge PDF files securely in your browser.",
    "pdfTitle": "Công cụ PDF"
  },
  "bn": {
    "imageToolsTitle": "ইমেজ টুলস",
    "imageToolsDesc": "ইমেজ টুলস: compress, rotate and convert images privately in your browser.",
    "open": "টুল খুলুন",
    "compressTitle": "ইমেজ কমপ্রেস ও রোটেট",
    "compressDesc": "Reduce image file size and rotate before download.",
    "convertTitle": "JPG থেকে PNG কনভার্টার",
    "convertDesc": "Convert JPG images to PNG directly in your browser.",
    "choose": "ইমেজ টুলস",
    "noImage": "No image selected",
    "download": "ডাউনলোড",
    "preview": "Preview",
    "privacy": "Your image is processed locally in your browser. We do not upload or store your files.",
    "quality": "Quality",
    "downloadCompressed": "ডাউনলোড",
    "originalSize": "Original size",
    "newSize": "Estimated new size",
    "actualNewSize": "Downloaded size",
    "rotateLeft": "Rotate Left",
    "rotateRight": "Rotate Right",
    "rotation": "Rotation",
    "convert": "Convert to PNG",
    "downloadPng": "ডাউনলোড",
    "fast": "Fast",
    "secure": "Secure",
    "free": "Free",
    "mobile": "Mobile Friendly",
    "homeTitle": "ফ্রি অনলাইন টুলস",
    "homeDesc": "Choose PDF tools or image tools. Files stay private in your browser.",
    "pdfCategory": "PDF টুলস",
    "imageCategory": "ইমেজ টুলস",
    "pdfDesc": "Convert images to PDF and merge PDF files securely in your browser.",
    "pdfTitle": "PDF টুলস"
  },
  "ur": {
    "imageToolsTitle": "امیج ٹولز",
    "imageToolsDesc": "امیج ٹولز: compress, rotate and convert images privately in your browser.",
    "open": "ٹول کھولیں",
    "compressTitle": "تصویر کمپریس اور روٹیٹ کریں",
    "compressDesc": "Reduce image file size and rotate before download.",
    "convertTitle": "JPG سے PNG کنورٹر",
    "convertDesc": "Convert JPG images to PNG directly in your browser.",
    "choose": "امیج ٹولز",
    "noImage": "No image selected",
    "download": "ڈاؤن لوڈ",
    "preview": "Preview",
    "privacy": "Your image is processed locally in your browser. We do not upload or store your files.",
    "quality": "Quality",
    "downloadCompressed": "ڈاؤن لوڈ",
    "originalSize": "Original size",
    "newSize": "Estimated new size",
    "actualNewSize": "Downloaded size",
    "rotateLeft": "Rotate Left",
    "rotateRight": "Rotate Right",
    "rotation": "Rotation",
    "convert": "Convert to PNG",
    "downloadPng": "ڈاؤن لوڈ",
    "fast": "Fast",
    "secure": "Secure",
    "free": "Free",
    "mobile": "Mobile Friendly",
    "homeTitle": "مفت آن لائن ٹولز",
    "homeDesc": "Choose PDF tools or image tools. Files stay private in your browser.",
    "pdfCategory": "PDF ٹولز",
    "imageCategory": "امیج ٹولز",
    "pdfDesc": "Convert images to PDF and merge PDF files securely in your browser.",
    "pdfTitle": "PDF ٹولز"
  },
  "fa": {
    "imageToolsTitle": "ابزارهای تصویر",
    "imageToolsDesc": "ابزارهای تصویر: compress, rotate and convert images privately in your browser.",
    "open": "باز کردن ابزار",
    "compressTitle": "فشرده‌سازی و چرخش تصویر",
    "compressDesc": "Reduce image file size and rotate before download.",
    "convertTitle": "تبدیل JPG به PNG",
    "convertDesc": "Convert JPG images to PNG directly in your browser.",
    "choose": "ابزارهای تصویر",
    "noImage": "No image selected",
    "download": "دانلود",
    "preview": "Preview",
    "privacy": "Your image is processed locally in your browser. We do not upload or store your files.",
    "quality": "Quality",
    "downloadCompressed": "دانلود",
    "originalSize": "Original size",
    "newSize": "Estimated new size",
    "actualNewSize": "Downloaded size",
    "rotateLeft": "Rotate Left",
    "rotateRight": "Rotate Right",
    "rotation": "Rotation",
    "convert": "Convert to PNG",
    "downloadPng": "دانلود",
    "fast": "Fast",
    "secure": "Secure",
    "free": "Free",
    "mobile": "Mobile Friendly",
    "homeTitle": "ابزارهای آنلاین رایگان",
    "homeDesc": "Choose PDF tools or image tools. Files stay private in your browser.",
    "pdfCategory": "ابزارهای PDF",
    "imageCategory": "ابزارهای تصویر",
    "pdfDesc": "Convert images to PDF and merge PDF files securely in your browser.",
    "pdfTitle": "ابزارهای PDF"
  },
  "ms": {
    "imageToolsTitle": "Alat Imej",
    "imageToolsDesc": "Alat Imej: compress, rotate and convert images privately in your browser.",
    "open": "Buka Alat",
    "compressTitle": "Mampat & Putar Imej",
    "compressDesc": "Reduce image file size and rotate before download.",
    "convertTitle": "Penukar JPG ke PNG",
    "convertDesc": "Convert JPG images to PNG directly in your browser.",
    "choose": "Alat Imej",
    "noImage": "No image selected",
    "download": "Muat turun",
    "preview": "Preview",
    "privacy": "Your image is processed locally in your browser. We do not upload or store your files.",
    "quality": "Quality",
    "downloadCompressed": "Muat turun",
    "originalSize": "Original size",
    "newSize": "Estimated new size",
    "actualNewSize": "Downloaded size",
    "rotateLeft": "Rotate Left",
    "rotateRight": "Rotate Right",
    "rotation": "Rotation",
    "convert": "Convert to PNG",
    "downloadPng": "Muat turun",
    "fast": "Fast",
    "secure": "Secure",
    "free": "Free",
    "mobile": "Mobile Friendly",
    "homeTitle": "Alat Online Percuma",
    "homeDesc": "Choose PDF tools or image tools. Files stay private in your browser.",
    "pdfCategory": "Alat PDF",
    "imageCategory": "Alat Imej",
    "pdfDesc": "Convert images to PDF and merge PDF files securely in your browser.",
    "pdfTitle": "Alat PDF"
  }
};
export function getImageToolText(lang){ return imageToolText[lang] || imageToolText.en; }
