export const imageToolText = {
  "en": {
    "imageToolsTitle": "Image Tools",
    "imageToolsDesc": "Crop, resize, compress and convert images privately in your browser.",
    "open": "Open Tool",
    "cropTitle": "Crop Image",
    "cropDesc": "Select a rectangular area and crop your image without upload.",
    "resizeTitle": "Resize Image",
    "resizeDesc": "Set exact width and height using input boxes.",
    "compressTitle": "Compress Image",
    "compressDesc": "Reduce image file size while keeping good quality.",
    "convertTitle": "JPG to PNG Converter",
    "convertDesc": "Convert JPG images to PNG directly in your browser.",
    "choose": "Choose Image",
    "noImage": "No image selected",
    "download": "Download",
    "reset": "Reset",
    "preview": "Preview",
    "privacy": "Your image is processed locally in your browser. We do not upload or store your files.",
    "cropHelp": "Click and drag on the image to draw a rectangular crop box. Move your finger or mouse, release, then click download.",
    "downloadCrop": "Download Cropped Image",
    "width": "Width",
    "height": "Height",
    "keepRatio": "Keep aspect ratio",
    "downloadResize": "Download Resized Image",
    "quality": "Quality",
    "downloadCompressed": "Download Compressed Image",
    "originalSize": "Original size",
    "newSize": "Estimated new size",
    "actualNewSize": "Downloaded size",
    "convert": "Convert to PNG",
    "downloadPng": "Download PNG",
    "selectArea": "Selected area",
    "dragTip": "Tip: start from one corner of the area and drag to the opposite corner.",
    "fast": "Fast",
    "secure": "Secure",
    "free": "Free",
    "mobile": "Mobile Friendly",
    "homeTitle": "Free Online Tools",
    "homeDesc": "Choose PDF tools or image tools. Files stay private in your browser.",
    "pdfCategory": "PDF Tools",
    "imageCategory": "Image Tools",
    "pdfDesc": "Convert images to PDF and merge PDF files securely in your browser.",
    "pdfTitle": "PDF Tools"
  },
  "hi": {
    "imageToolsTitle": "इमेज टूल्स",
    "imageToolsDesc": "इमेज को ब्राउज़र में ही क्रॉप, रीसाइज़, कंप्रेस और कन्वर्ट करें।",
    "open": "टूल खोलें",
    "cropTitle": "इमेज क्रॉप करें",
    "cropDesc": "Rectangular area चुनकर इमेज crop करें।",
    "resizeTitle": "इमेज रीसाइज़ करें",
    "resizeDesc": "Width और height input box से exact size सेट करें।",
    "compressTitle": "इमेज कंप्रेस करें",
    "compressDesc": "अच्छी quality रखते हुए image file size कम करें।",
    "convertTitle": "JPG से PNG कन्वर्टर",
    "convertDesc": "JPG इमेज को सीधे ब्राउज़र में PNG बनाएं।",
    "choose": "इमेज चुनें",
    "noImage": "कोई इमेज चुनी नहीं गई",
    "download": "डाउनलोड",
    "reset": "रीसेट",
    "preview": "प्रीव्यू",
    "privacy": "आपकी इमेज आपके ब्राउज़र में ही प्रोसेस होती है। हम फाइल upload या store नहीं करते।",
    "cropHelp": "इमेज पर click/drag करके rectangular crop box बनाएं, फिर download पर क्लिक करें।",
    "downloadCrop": "क्रॉप इमेज डाउनलोड करें",
    "width": "चौड़ाई",
    "height": "ऊंचाई",
    "keepRatio": "Aspect ratio रखें",
    "downloadResize": "रीसाइज़ इमेज डाउनलोड करें",
    "quality": "क्वालिटी",
    "downloadCompressed": "कंप्रेस इमेज डाउनलोड करें",
    "originalSize": "Original size",
    "newSize": "Estimated new size",
    "actualNewSize": "Downloaded size",
    "convert": "PNG में बदलें",
    "downloadPng": "PNG डाउनलोड करें",
    "selectArea": "चुना हुआ area",
    "dragTip": "Tip: एक corner से शुरू करके दूसरे corner तक drag करें।",
    "fast": "तेज़",
    "secure": "सुरक्षित",
    "free": "मुफ्त",
    "mobile": "Mobile Friendly",
    "homeTitle": "मुफ्त ऑनलाइन टूल्स",
    "homeDesc": "PDF tools या image tools चुनें। Files आपके browser में private रहती हैं।",
    "pdfCategory": "PDF टूल्स",
    "imageCategory": "इमेज टूल्स",
    "pdfDesc": "इमेज को PDF में बदलें और PDF files को browser में safely merge करें।",
    "pdfTitle": "PDF टूल्स"
  },
  "ar": {
    "imageToolsTitle": "أدوات الصور",
    "imageToolsDesc": "قص الصور وتغيير حجمها وضغطها وتحويلها داخل المتصفح.",
    "open": "افتح الأداة",
    "cropTitle": "قص الصورة",
    "cropDesc": "حدد منطقة مستطيلة واقص الصورة بدون رفعها.",
    "resizeTitle": "تغيير حجم الصورة",
    "resizeDesc": "حدد العرض والارتفاع بدقة من الخانات.",
    "compressTitle": "ضغط الصورة",
    "compressDesc": "قلل حجم الصورة مع الحفاظ على جودة جيدة.",
    "convertTitle": "تحويل JPG إلى PNG",
    "convertDesc": "حوّل صور JPG إلى PNG داخل المتصفح.",
    "choose": "اختر صورة",
    "noImage": "لم يتم اختيار صورة",
    "download": "تنزيل",
    "reset": "إعادة ضبط",
    "preview": "معاينة",
    "privacy": "تتم معالجة صورتك محلياً داخل المتصفح. لا نرفع أو نخزن ملفاتك.",
    "cropHelp": "اضغط واسحب على الصورة لرسم مربع قص مستطيل، ثم اضغط تنزيل.",
    "downloadCrop": "تنزيل الصورة المقصوصة",
    "width": "العرض",
    "height": "الارتفاع",
    "keepRatio": "الحفاظ على النسبة",
    "downloadResize": "تنزيل الصورة بعد تغيير الحجم",
    "quality": "الجودة",
    "downloadCompressed": "تنزيل الصورة المضغوطة",
    "originalSize": "الحجم الأصلي",
    "newSize": "الحجم الجديد المتوقع",
    "actualNewSize": "حجم التنزيل",
    "convert": "تحويل إلى PNG",
    "downloadPng": "تنزيل PNG",
    "selectArea": "المنطقة المحددة",
    "dragTip": "نصيحة: اسحب من زاوية المنطقة إلى الزاوية المقابلة.",
    "fast": "سريع",
    "secure": "آمن",
    "free": "مجاني",
    "mobile": "مناسب للجوال",
    "homeTitle": "أدوات مجانية على الإنترنت",
    "homeDesc": "اختر أدوات PDF أو الصور. تبقى ملفاتك خاصة في المتصفح.",
    "pdfCategory": "أدوات PDF",
    "imageCategory": "أدوات الصور",
    "pdfDesc": "حوّل الصور إلى PDF وادمج ملفات PDF بأمان في المتصفح.",
    "pdfTitle": "أدوات PDF"
  },
  "ru": {
    "imageToolsTitle": "Инструменты для изображений",
    "imageToolsDesc": "Обрезайте, изменяйте размер, сжимайте и конвертируйте изображения прямо в браузере.",
    "open": "Открыть инструмент",
    "cropTitle": "Обрезать изображение",
    "cropDesc": "Выберите прямоугольную область и обрежьте изображение без загрузки.",
    "resizeTitle": "Изменить размер изображения",
    "resizeDesc": "Задайте точную ширину и высоту в полях ввода.",
    "compressTitle": "Сжать изображение",
    "compressDesc": "Уменьшите размер файла с сохранением хорошего качества.",
    "convertTitle": "Конвертер JPG в PNG",
    "convertDesc": "Конвертируйте JPG в PNG прямо в браузере.",
    "choose": "Выбрать изображение",
    "noImage": "Изображение не выбрано",
    "download": "Скачать",
    "reset": "Сбросить",
    "preview": "Предпросмотр",
    "privacy": "Ваше изображение обрабатывается локально в браузере. Мы не загружаем и не храним файлы.",
    "cropHelp": "Нажмите и перетащите по изображению, чтобы создать прямоугольную область обрезки, затем нажмите скачать.",
    "downloadCrop": "Скачать обрезанное изображение",
    "width": "Ширина",
    "height": "Высота",
    "keepRatio": "Сохранять пропорции",
    "downloadResize": "Скачать изменённое изображение",
    "quality": "Качество",
    "downloadCompressed": "Скачать сжатое изображение",
    "originalSize": "Исходный размер",
    "newSize": "Ожидаемый новый размер",
    "actualNewSize": "Размер скачанного файла",
    "convert": "Конвертировать в PNG",
    "downloadPng": "Скачать PNG",
    "selectArea": "Выбранная область",
    "dragTip": "Совет: начните с одного угла области и тяните к противоположному углу.",
    "fast": "Быстро",
    "secure": "Безопасно",
    "free": "Бесплатно",
    "mobile": "Для телефона",
    "homeTitle": "Бесплатные онлайн-инструменты",
    "homeDesc": "Выберите PDF или Image инструменты. Файлы остаются приватными в браузере.",
    "pdfCategory": "PDF Инструменты",
    "imageCategory": "Инструменты для изображений",
    "pdfDesc": "Конвертируйте изображения в PDF и объединяйте PDF безопасно в браузере.",
    "pdfTitle": "PDF Инструменты"
  },
  "zh-CN": {
    "imageToolsTitle": "图片工具",
    "imageToolsDesc": "在浏览器中私密裁剪、调整大小、压缩和转换图片。",
    "open": "打开工具",
    "cropTitle": "裁剪图片",
    "cropDesc": "选择矩形区域并裁剪图片，无需上传。",
    "resizeTitle": "调整图片大小",
    "resizeDesc": "用输入框设置准确宽度和高度。",
    "compressTitle": "压缩图片",
    "compressDesc": "减小图片文件大小并保持良好质量。",
    "convertTitle": "JPG 转 PNG",
    "convertDesc": "直接在浏览器中将 JPG 转为 PNG。",
    "choose": "选择图片",
    "noImage": "未选择图片",
    "download": "下载",
    "reset": "重置",
    "preview": "预览",
    "privacy": "图片只在浏览器中本地处理。我们不会上传或存储文件。",
    "cropHelp": "在图片上点击并拖动绘制矩形裁剪框，然后点击下载。",
    "downloadCrop": "下载裁剪图片",
    "width": "宽度",
    "height": "高度",
    "keepRatio": "保持比例",
    "downloadResize": "下载调整后的图片",
    "quality": "质量",
    "downloadCompressed": "下载压缩图片",
    "originalSize": "原始大小",
    "newSize": "预计新大小",
    "actualNewSize": "下载大小",
    "convert": "转换为 PNG",
    "downloadPng": "下载 PNG",
    "selectArea": "选择区域",
    "dragTip": "提示：从一个角拖到对角。",
    "fast": "快速",
    "secure": "安全",
    "free": "免费",
    "mobile": "适合手机",
    "homeTitle": "免费在线工具",
    "homeDesc": "选择 PDF 工具或图片工具。文件保留在浏览器中。",
    "pdfCategory": "PDF 工具",
    "imageCategory": "图片工具",
    "pdfDesc": "在浏览器中安全地将图片转为 PDF 并合并 PDF。",
    "pdfTitle": "PDF 工具"
  },
  "es": {
    "imageToolsTitle": "Herramientas de imagen",
    "imageToolsDesc": "Recorta, redimensiona, comprime y convierte imágenes en tu navegador.",
    "open": "Abrir herramienta",
    "cropTitle": "Recortar imagen",
    "cropDesc": "Selecciona un área rectangular y recorta sin subir archivos.",
    "resizeTitle": "Redimensionar imagen",
    "resizeDesc": "Define ancho y alto exactos.",
    "compressTitle": "Comprimir imagen",
    "compressDesc": "Reduce el tamaño manteniendo buena calidad.",
    "convertTitle": "Convertidor JPG a PNG",
    "convertDesc": "Convierte JPG a PNG en tu navegador.",
    "choose": "Elegir imagen",
    "noImage": "No hay imagen seleccionada",
    "download": "Descargar",
    "reset": "Restablecer",
    "preview": "Vista previa",
    "privacy": "Tu imagen se procesa localmente en el navegador. No subimos ni guardamos tus archivos.",
    "cropHelp": "Haz clic y arrastra para dibujar un rectángulo de recorte, luego descarga.",
    "downloadCrop": "Descargar imagen recortada",
    "width": "Ancho",
    "height": "Alto",
    "keepRatio": "Mantener proporción",
    "downloadResize": "Descargar imagen redimensionada",
    "quality": "Calidad",
    "downloadCompressed": "Descargar imagen comprimida",
    "originalSize": "Tamaño original",
    "newSize": "Nuevo tamaño estimado",
    "actualNewSize": "Tamaño descargado",
    "convert": "Convertir a PNG",
    "downloadPng": "Descargar PNG",
    "selectArea": "Área seleccionada",
    "dragTip": "Consejo: arrastra de una esquina a la opuesta.",
    "fast": "Rápido",
    "secure": "Seguro",
    "free": "Gratis",
    "mobile": "Móvil",
    "homeTitle": "Herramientas gratis online",
    "homeDesc": "Elige herramientas PDF o de imagen. Tus archivos quedan en el navegador.",
    "pdfCategory": "Herramientas PDF",
    "imageCategory": "Herramientas de imagen",
    "pdfDesc": "Convierte imágenes a PDF y une PDF en tu navegador.",
    "pdfTitle": "Herramientas PDF"
  },
  "fr": {
    "imageToolsTitle": "Outils d’image",
    "imageToolsDesc": "Recadrez, redimensionnez, compressez et convertissez dans le navigateur.",
    "open": "Ouvrir l’outil",
    "cropTitle": "Recadrer une image",
    "cropDesc": "Sélectionnez une zone rectangulaire sans téléverser.",
    "resizeTitle": "Redimensionner une image",
    "resizeDesc": "Définissez largeur et hauteur exactes.",
    "compressTitle": "Compresser une image",
    "compressDesc": "Réduisez la taille en gardant une bonne qualité.",
    "convertTitle": "Convertisseur JPG en PNG",
    "convertDesc": "Convertissez JPG en PNG dans le navigateur.",
    "choose": "Choisir une image",
    "noImage": "Aucune image sélectionnée",
    "download": "Télécharger",
    "reset": "Réinitialiser",
    "preview": "Aperçu",
    "privacy": "Votre image est traitée localement dans le navigateur. Nous ne téléversons ni ne stockons vos fichiers.",
    "cropHelp": "Cliquez et faites glisser pour dessiner une zone rectangulaire, puis téléchargez.",
    "downloadCrop": "Télécharger l’image recadrée",
    "width": "Largeur",
    "height": "Hauteur",
    "keepRatio": "Conserver les proportions",
    "downloadResize": "Télécharger l’image redimensionnée",
    "quality": "Qualité",
    "downloadCompressed": "Télécharger l’image compressée",
    "originalSize": "Taille originale",
    "newSize": "Nouvelle taille estimée",
    "actualNewSize": "Taille téléchargée",
    "convert": "Convertir en PNG",
    "downloadPng": "Télécharger PNG",
    "selectArea": "Zone sélectionnée",
    "dragTip": "Astuce : faites glisser d’un coin à l’autre.",
    "fast": "Rapide",
    "secure": "Sécurisé",
    "free": "Gratuit",
    "mobile": "Mobile",
    "homeTitle": "Outils gratuits en ligne",
    "homeDesc": "Choisissez des outils PDF ou image. Les fichiers restent dans votre navigateur.",
    "pdfCategory": "Outils PDF",
    "imageCategory": "Outils d’image",
    "pdfDesc": "Convertissez des images en PDF et fusionnez des PDF dans le navigateur.",
    "pdfTitle": "Outils PDF"
  },
  "de": {
    "imageToolsTitle": "Bild-Tools",
    "imageToolsDesc": "Bilder im Browser zuschneiden, skalieren, komprimieren und konvertieren.",
    "open": "Tool öffnen",
    "cropTitle": "Bild zuschneiden",
    "cropDesc": "Wählen Sie einen rechteckigen Bereich ohne Upload.",
    "resizeTitle": "Bildgröße ändern",
    "resizeDesc": "Exakte Breite und Höhe eingeben.",
    "compressTitle": "Bild komprimieren",
    "compressDesc": "Dateigröße reduzieren bei guter Qualität.",
    "convertTitle": "JPG zu PNG",
    "convertDesc": "JPG direkt im Browser in PNG umwandeln.",
    "choose": "Bild wählen",
    "noImage": "Kein Bild ausgewählt",
    "download": "Herunterladen",
    "reset": "Zurücksetzen",
    "preview": "Vorschau",
    "privacy": "Ihr Bild wird lokal im Browser verarbeitet. Wir laden oder speichern keine Dateien.",
    "cropHelp": "Klicken und ziehen Sie einen rechteckigen Zuschnittbereich, dann herunterladen.",
    "downloadCrop": "Zugeschnittenes Bild herunterladen",
    "width": "Breite",
    "height": "Höhe",
    "keepRatio": "Seitenverhältnis beibehalten",
    "downloadResize": "Skaliertes Bild herunterladen",
    "quality": "Qualität",
    "downloadCompressed": "Komprimiertes Bild herunterladen",
    "originalSize": "Originalgröße",
    "newSize": "Geschätzte neue Größe",
    "actualNewSize": "Downloadgröße",
    "convert": "In PNG umwandeln",
    "downloadPng": "PNG herunterladen",
    "selectArea": "Ausgewählter Bereich",
    "dragTip": "Tipp: von einer Ecke zur gegenüberliegenden ziehen.",
    "fast": "Schnell",
    "secure": "Sicher",
    "free": "Kostenlos",
    "mobile": "Mobilfreundlich",
    "homeTitle": "Kostenlose Online-Tools",
    "homeDesc": "Wählen Sie PDF- oder Bild-Tools. Dateien bleiben im Browser.",
    "pdfCategory": "PDF-Tools",
    "imageCategory": "Bild-Tools",
    "pdfDesc": "Bilder in PDF umwandeln und PDFs im Browser zusammenführen.",
    "pdfTitle": "PDF-Tools"
  },
  "pt": {
    "imageToolsTitle": "Ferramentas de imagem",
    "imageToolsDesc": "Edit, resize, compress and convert images privately in your browser.",
    "open": "Abrir ferramenta",
    "cropTitle": "Crop Image",
    "cropDesc": "Select a rectangular area and crop your image without upload.",
    "resizeTitle": "Resize Image",
    "resizeDesc": "Set exact width and height using input boxes.",
    "compressTitle": "Compress Image",
    "compressDesc": "Reduce image file size while keeping good quality.",
    "convertTitle": "JPG to PNG Converter",
    "convertDesc": "Convert JPG images to PNG directly in your browser.",
    "choose": "Choose Image",
    "noImage": "No image selected",
    "download": "Download",
    "reset": "Reset",
    "preview": "Preview",
    "privacy": "Your image is processed locally in your browser. We do not upload or store your files.",
    "cropHelp": "Click and drag on the image to draw a rectangular crop box. Move your finger or mouse, release, then click download.",
    "downloadCrop": "Download Cropped Image",
    "width": "Width",
    "height": "Height",
    "keepRatio": "Keep aspect ratio",
    "downloadResize": "Download Resized Image",
    "quality": "Quality",
    "downloadCompressed": "Download Compressed Image",
    "originalSize": "Original size",
    "newSize": "Estimated new size",
    "actualNewSize": "Downloaded size",
    "convert": "Convert to PNG",
    "downloadPng": "Download PNG",
    "selectArea": "Selected area",
    "dragTip": "Tip: start from one corner of the area and drag to the opposite corner.",
    "fast": "Fast",
    "secure": "Secure",
    "free": "Free",
    "mobile": "Mobile Friendly",
    "homeTitle": "Ferramentas online gratuitas",
    "homeDesc": "Choose PDF tools or image tools. Files stay private in your browser.",
    "pdfCategory": "Ferramentas PDF",
    "imageCategory": "Ferramentas de imagem",
    "pdfDesc": "Convert images to PDF and merge PDF files securely in your browser.",
    "pdfTitle": "Ferramentas PDF"
  },
  "ja": {
    "imageToolsTitle": "画像ツール",
    "imageToolsDesc": "Edit, resize, compress and convert images privately in your browser.",
    "open": "ツールを開く",
    "cropTitle": "Crop Image",
    "cropDesc": "Select a rectangular area and crop your image without upload.",
    "resizeTitle": "Resize Image",
    "resizeDesc": "Set exact width and height using input boxes.",
    "compressTitle": "Compress Image",
    "compressDesc": "Reduce image file size while keeping good quality.",
    "convertTitle": "JPG to PNG Converter",
    "convertDesc": "Convert JPG images to PNG directly in your browser.",
    "choose": "Choose Image",
    "noImage": "No image selected",
    "download": "Download",
    "reset": "Reset",
    "preview": "Preview",
    "privacy": "Your image is processed locally in your browser. We do not upload or store your files.",
    "cropHelp": "Click and drag on the image to draw a rectangular crop box. Move your finger or mouse, release, then click download.",
    "downloadCrop": "Download Cropped Image",
    "width": "Width",
    "height": "Height",
    "keepRatio": "Keep aspect ratio",
    "downloadResize": "Download Resized Image",
    "quality": "Quality",
    "downloadCompressed": "Download Compressed Image",
    "originalSize": "Original size",
    "newSize": "Estimated new size",
    "actualNewSize": "Downloaded size",
    "convert": "Convert to PNG",
    "downloadPng": "Download PNG",
    "selectArea": "Selected area",
    "dragTip": "Tip: start from one corner of the area and drag to the opposite corner.",
    "fast": "Fast",
    "secure": "Secure",
    "free": "Free",
    "mobile": "Mobile Friendly",
    "homeTitle": "無料オンラインツール",
    "homeDesc": "Choose PDF tools or image tools. Files stay private in your browser.",
    "pdfCategory": "PDF ツール",
    "imageCategory": "画像ツール",
    "pdfDesc": "Convert images to PDF and merge PDF files securely in your browser.",
    "pdfTitle": "PDF ツール"
  },
  "id": {
    "imageToolsTitle": "Alat Gambar",
    "imageToolsDesc": "Edit, resize, compress and convert images privately in your browser.",
    "open": "Buka Alat",
    "cropTitle": "Crop Image",
    "cropDesc": "Select a rectangular area and crop your image without upload.",
    "resizeTitle": "Resize Image",
    "resizeDesc": "Set exact width and height using input boxes.",
    "compressTitle": "Compress Image",
    "compressDesc": "Reduce image file size while keeping good quality.",
    "convertTitle": "JPG to PNG Converter",
    "convertDesc": "Convert JPG images to PNG directly in your browser.",
    "choose": "Choose Image",
    "noImage": "No image selected",
    "download": "Download",
    "reset": "Reset",
    "preview": "Preview",
    "privacy": "Your image is processed locally in your browser. We do not upload or store your files.",
    "cropHelp": "Click and drag on the image to draw a rectangular crop box. Move your finger or mouse, release, then click download.",
    "downloadCrop": "Download Cropped Image",
    "width": "Width",
    "height": "Height",
    "keepRatio": "Keep aspect ratio",
    "downloadResize": "Download Resized Image",
    "quality": "Quality",
    "downloadCompressed": "Download Compressed Image",
    "originalSize": "Original size",
    "newSize": "Estimated new size",
    "actualNewSize": "Downloaded size",
    "convert": "Convert to PNG",
    "downloadPng": "Download PNG",
    "selectArea": "Selected area",
    "dragTip": "Tip: start from one corner of the area and drag to the opposite corner.",
    "fast": "Fast",
    "secure": "Secure",
    "free": "Free",
    "mobile": "Mobile Friendly",
    "homeTitle": "Alat Online Gratis",
    "homeDesc": "Choose PDF tools or image tools. Files stay private in your browser.",
    "pdfCategory": "Alat PDF",
    "imageCategory": "Alat Gambar",
    "pdfDesc": "Convert images to PDF and merge PDF files securely in your browser.",
    "pdfTitle": "Alat PDF"
  },
  "tr": {
    "imageToolsTitle": "Görsel Araçları",
    "imageToolsDesc": "Edit, resize, compress and convert images privately in your browser.",
    "open": "Aracı Aç",
    "cropTitle": "Crop Image",
    "cropDesc": "Select a rectangular area and crop your image without upload.",
    "resizeTitle": "Resize Image",
    "resizeDesc": "Set exact width and height using input boxes.",
    "compressTitle": "Compress Image",
    "compressDesc": "Reduce image file size while keeping good quality.",
    "convertTitle": "JPG to PNG Converter",
    "convertDesc": "Convert JPG images to PNG directly in your browser.",
    "choose": "Choose Image",
    "noImage": "No image selected",
    "download": "Download",
    "reset": "Reset",
    "preview": "Preview",
    "privacy": "Your image is processed locally in your browser. We do not upload or store your files.",
    "cropHelp": "Click and drag on the image to draw a rectangular crop box. Move your finger or mouse, release, then click download.",
    "downloadCrop": "Download Cropped Image",
    "width": "Width",
    "height": "Height",
    "keepRatio": "Keep aspect ratio",
    "downloadResize": "Download Resized Image",
    "quality": "Quality",
    "downloadCompressed": "Download Compressed Image",
    "originalSize": "Original size",
    "newSize": "Estimated new size",
    "actualNewSize": "Downloaded size",
    "convert": "Convert to PNG",
    "downloadPng": "Download PNG",
    "selectArea": "Selected area",
    "dragTip": "Tip: start from one corner of the area and drag to the opposite corner.",
    "fast": "Fast",
    "secure": "Secure",
    "free": "Free",
    "mobile": "Mobile Friendly",
    "homeTitle": "Ücretsiz Online Araçlar",
    "homeDesc": "Choose PDF tools or image tools. Files stay private in your browser.",
    "pdfCategory": "PDF Araçları",
    "imageCategory": "Görsel Araçları",
    "pdfDesc": "Convert images to PDF and merge PDF files securely in your browser.",
    "pdfTitle": "PDF Araçları"
  },
  "ko": {
    "imageToolsTitle": "이미지 도구",
    "imageToolsDesc": "Edit, resize, compress and convert images privately in your browser.",
    "open": "도구 열기",
    "cropTitle": "Crop Image",
    "cropDesc": "Select a rectangular area and crop your image without upload.",
    "resizeTitle": "Resize Image",
    "resizeDesc": "Set exact width and height using input boxes.",
    "compressTitle": "Compress Image",
    "compressDesc": "Reduce image file size while keeping good quality.",
    "convertTitle": "JPG to PNG Converter",
    "convertDesc": "Convert JPG images to PNG directly in your browser.",
    "choose": "Choose Image",
    "noImage": "No image selected",
    "download": "Download",
    "reset": "Reset",
    "preview": "Preview",
    "privacy": "Your image is processed locally in your browser. We do not upload or store your files.",
    "cropHelp": "Click and drag on the image to draw a rectangular crop box. Move your finger or mouse, release, then click download.",
    "downloadCrop": "Download Cropped Image",
    "width": "Width",
    "height": "Height",
    "keepRatio": "Keep aspect ratio",
    "downloadResize": "Download Resized Image",
    "quality": "Quality",
    "downloadCompressed": "Download Compressed Image",
    "originalSize": "Original size",
    "newSize": "Estimated new size",
    "actualNewSize": "Downloaded size",
    "convert": "Convert to PNG",
    "downloadPng": "Download PNG",
    "selectArea": "Selected area",
    "dragTip": "Tip: start from one corner of the area and drag to the opposite corner.",
    "fast": "Fast",
    "secure": "Secure",
    "free": "Free",
    "mobile": "Mobile Friendly",
    "homeTitle": "무료 온라인 도구",
    "homeDesc": "Choose PDF tools or image tools. Files stay private in your browser.",
    "pdfCategory": "PDF 도구",
    "imageCategory": "이미지 도구",
    "pdfDesc": "Convert images to PDF and merge PDF files securely in your browser.",
    "pdfTitle": "PDF 도구"
  },
  "it": {
    "imageToolsTitle": "Strumenti immagine",
    "imageToolsDesc": "Edit, resize, compress and convert images privately in your browser.",
    "open": "Apri strumento",
    "cropTitle": "Crop Image",
    "cropDesc": "Select a rectangular area and crop your image without upload.",
    "resizeTitle": "Resize Image",
    "resizeDesc": "Set exact width and height using input boxes.",
    "compressTitle": "Compress Image",
    "compressDesc": "Reduce image file size while keeping good quality.",
    "convertTitle": "JPG to PNG Converter",
    "convertDesc": "Convert JPG images to PNG directly in your browser.",
    "choose": "Choose Image",
    "noImage": "No image selected",
    "download": "Download",
    "reset": "Reset",
    "preview": "Preview",
    "privacy": "Your image is processed locally in your browser. We do not upload or store your files.",
    "cropHelp": "Click and drag on the image to draw a rectangular crop box. Move your finger or mouse, release, then click download.",
    "downloadCrop": "Download Cropped Image",
    "width": "Width",
    "height": "Height",
    "keepRatio": "Keep aspect ratio",
    "downloadResize": "Download Resized Image",
    "quality": "Quality",
    "downloadCompressed": "Download Compressed Image",
    "originalSize": "Original size",
    "newSize": "Estimated new size",
    "actualNewSize": "Downloaded size",
    "convert": "Convert to PNG",
    "downloadPng": "Download PNG",
    "selectArea": "Selected area",
    "dragTip": "Tip: start from one corner of the area and drag to the opposite corner.",
    "fast": "Fast",
    "secure": "Secure",
    "free": "Free",
    "mobile": "Mobile Friendly",
    "homeTitle": "Strumenti online gratuiti",
    "homeDesc": "Choose PDF tools or image tools. Files stay private in your browser.",
    "pdfCategory": "Strumenti PDF",
    "imageCategory": "Strumenti immagine",
    "pdfDesc": "Convert images to PDF and merge PDF files securely in your browser.",
    "pdfTitle": "Strumenti PDF"
  },
  "nl": {
    "imageToolsTitle": "Afbeeldingstools",
    "imageToolsDesc": "Edit, resize, compress and convert images privately in your browser.",
    "open": "Tool openen",
    "cropTitle": "Crop Image",
    "cropDesc": "Select a rectangular area and crop your image without upload.",
    "resizeTitle": "Resize Image",
    "resizeDesc": "Set exact width and height using input boxes.",
    "compressTitle": "Compress Image",
    "compressDesc": "Reduce image file size while keeping good quality.",
    "convertTitle": "JPG to PNG Converter",
    "convertDesc": "Convert JPG images to PNG directly in your browser.",
    "choose": "Choose Image",
    "noImage": "No image selected",
    "download": "Download",
    "reset": "Reset",
    "preview": "Preview",
    "privacy": "Your image is processed locally in your browser. We do not upload or store your files.",
    "cropHelp": "Click and drag on the image to draw a rectangular crop box. Move your finger or mouse, release, then click download.",
    "downloadCrop": "Download Cropped Image",
    "width": "Width",
    "height": "Height",
    "keepRatio": "Keep aspect ratio",
    "downloadResize": "Download Resized Image",
    "quality": "Quality",
    "downloadCompressed": "Download Compressed Image",
    "originalSize": "Original size",
    "newSize": "Estimated new size",
    "actualNewSize": "Downloaded size",
    "convert": "Convert to PNG",
    "downloadPng": "Download PNG",
    "selectArea": "Selected area",
    "dragTip": "Tip: start from one corner of the area and drag to the opposite corner.",
    "fast": "Fast",
    "secure": "Secure",
    "free": "Free",
    "mobile": "Mobile Friendly",
    "homeTitle": "Gratis online tools",
    "homeDesc": "Choose PDF tools or image tools. Files stay private in your browser.",
    "pdfCategory": "PDF-tools",
    "imageCategory": "Afbeeldingstools",
    "pdfDesc": "Convert images to PDF and merge PDF files securely in your browser.",
    "pdfTitle": "PDF-tools"
  },
  "pl": {
    "imageToolsTitle": "Narzędzia obrazów",
    "imageToolsDesc": "Edit, resize, compress and convert images privately in your browser.",
    "open": "Otwórz narzędzie",
    "cropTitle": "Crop Image",
    "cropDesc": "Select a rectangular area and crop your image without upload.",
    "resizeTitle": "Resize Image",
    "resizeDesc": "Set exact width and height using input boxes.",
    "compressTitle": "Compress Image",
    "compressDesc": "Reduce image file size while keeping good quality.",
    "convertTitle": "JPG to PNG Converter",
    "convertDesc": "Convert JPG images to PNG directly in your browser.",
    "choose": "Choose Image",
    "noImage": "No image selected",
    "download": "Download",
    "reset": "Reset",
    "preview": "Preview",
    "privacy": "Your image is processed locally in your browser. We do not upload or store your files.",
    "cropHelp": "Click and drag on the image to draw a rectangular crop box. Move your finger or mouse, release, then click download.",
    "downloadCrop": "Download Cropped Image",
    "width": "Width",
    "height": "Height",
    "keepRatio": "Keep aspect ratio",
    "downloadResize": "Download Resized Image",
    "quality": "Quality",
    "downloadCompressed": "Download Compressed Image",
    "originalSize": "Original size",
    "newSize": "Estimated new size",
    "actualNewSize": "Downloaded size",
    "convert": "Convert to PNG",
    "downloadPng": "Download PNG",
    "selectArea": "Selected area",
    "dragTip": "Tip: start from one corner of the area and drag to the opposite corner.",
    "fast": "Fast",
    "secure": "Secure",
    "free": "Free",
    "mobile": "Mobile Friendly",
    "homeTitle": "Darmowe narzędzia online",
    "homeDesc": "Choose PDF tools or image tools. Files stay private in your browser.",
    "pdfCategory": "Narzędzia PDF",
    "imageCategory": "Narzędzia obrazów",
    "pdfDesc": "Convert images to PDF and merge PDF files securely in your browser.",
    "pdfTitle": "Narzędzia PDF"
  },
  "th": {
    "imageToolsTitle": "เครื่องมือรูปภาพ",
    "imageToolsDesc": "Edit, resize, compress and convert images privately in your browser.",
    "open": "เปิดเครื่องมือ",
    "cropTitle": "Crop Image",
    "cropDesc": "Select a rectangular area and crop your image without upload.",
    "resizeTitle": "Resize Image",
    "resizeDesc": "Set exact width and height using input boxes.",
    "compressTitle": "Compress Image",
    "compressDesc": "Reduce image file size while keeping good quality.",
    "convertTitle": "JPG to PNG Converter",
    "convertDesc": "Convert JPG images to PNG directly in your browser.",
    "choose": "Choose Image",
    "noImage": "No image selected",
    "download": "Download",
    "reset": "Reset",
    "preview": "Preview",
    "privacy": "Your image is processed locally in your browser. We do not upload or store your files.",
    "cropHelp": "Click and drag on the image to draw a rectangular crop box. Move your finger or mouse, release, then click download.",
    "downloadCrop": "Download Cropped Image",
    "width": "Width",
    "height": "Height",
    "keepRatio": "Keep aspect ratio",
    "downloadResize": "Download Resized Image",
    "quality": "Quality",
    "downloadCompressed": "Download Compressed Image",
    "originalSize": "Original size",
    "newSize": "Estimated new size",
    "actualNewSize": "Downloaded size",
    "convert": "Convert to PNG",
    "downloadPng": "Download PNG",
    "selectArea": "Selected area",
    "dragTip": "Tip: start from one corner of the area and drag to the opposite corner.",
    "fast": "Fast",
    "secure": "Secure",
    "free": "Free",
    "mobile": "Mobile Friendly",
    "homeTitle": "เครื่องมือออนไลน์ฟรี",
    "homeDesc": "Choose PDF tools or image tools. Files stay private in your browser.",
    "pdfCategory": "เครื่องมือ PDF",
    "imageCategory": "เครื่องมือรูปภาพ",
    "pdfDesc": "Convert images to PDF and merge PDF files securely in your browser.",
    "pdfTitle": "เครื่องมือ PDF"
  },
  "vi": {
    "imageToolsTitle": "Công cụ hình ảnh",
    "imageToolsDesc": "Edit, resize, compress and convert images privately in your browser.",
    "open": "Mở công cụ",
    "cropTitle": "Crop Image",
    "cropDesc": "Select a rectangular area and crop your image without upload.",
    "resizeTitle": "Resize Image",
    "resizeDesc": "Set exact width and height using input boxes.",
    "compressTitle": "Compress Image",
    "compressDesc": "Reduce image file size while keeping good quality.",
    "convertTitle": "JPG to PNG Converter",
    "convertDesc": "Convert JPG images to PNG directly in your browser.",
    "choose": "Choose Image",
    "noImage": "No image selected",
    "download": "Download",
    "reset": "Reset",
    "preview": "Preview",
    "privacy": "Your image is processed locally in your browser. We do not upload or store your files.",
    "cropHelp": "Click and drag on the image to draw a rectangular crop box. Move your finger or mouse, release, then click download.",
    "downloadCrop": "Download Cropped Image",
    "width": "Width",
    "height": "Height",
    "keepRatio": "Keep aspect ratio",
    "downloadResize": "Download Resized Image",
    "quality": "Quality",
    "downloadCompressed": "Download Compressed Image",
    "originalSize": "Original size",
    "newSize": "Estimated new size",
    "actualNewSize": "Downloaded size",
    "convert": "Convert to PNG",
    "downloadPng": "Download PNG",
    "selectArea": "Selected area",
    "dragTip": "Tip: start from one corner of the area and drag to the opposite corner.",
    "fast": "Fast",
    "secure": "Secure",
    "free": "Free",
    "mobile": "Mobile Friendly",
    "homeTitle": "Công cụ trực tuyến miễn phí",
    "homeDesc": "Choose PDF tools or image tools. Files stay private in your browser.",
    "pdfCategory": "Công cụ PDF",
    "imageCategory": "Công cụ hình ảnh",
    "pdfDesc": "Convert images to PDF and merge PDF files securely in your browser.",
    "pdfTitle": "Công cụ PDF"
  },
  "bn": {
    "imageToolsTitle": "ইমেজ টুলস",
    "imageToolsDesc": "Edit, resize, compress and convert images privately in your browser.",
    "open": "টুল খুলুন",
    "cropTitle": "Crop Image",
    "cropDesc": "Select a rectangular area and crop your image without upload.",
    "resizeTitle": "Resize Image",
    "resizeDesc": "Set exact width and height using input boxes.",
    "compressTitle": "Compress Image",
    "compressDesc": "Reduce image file size while keeping good quality.",
    "convertTitle": "JPG to PNG Converter",
    "convertDesc": "Convert JPG images to PNG directly in your browser.",
    "choose": "Choose Image",
    "noImage": "No image selected",
    "download": "Download",
    "reset": "Reset",
    "preview": "Preview",
    "privacy": "Your image is processed locally in your browser. We do not upload or store your files.",
    "cropHelp": "Click and drag on the image to draw a rectangular crop box. Move your finger or mouse, release, then click download.",
    "downloadCrop": "Download Cropped Image",
    "width": "Width",
    "height": "Height",
    "keepRatio": "Keep aspect ratio",
    "downloadResize": "Download Resized Image",
    "quality": "Quality",
    "downloadCompressed": "Download Compressed Image",
    "originalSize": "Original size",
    "newSize": "Estimated new size",
    "actualNewSize": "Downloaded size",
    "convert": "Convert to PNG",
    "downloadPng": "Download PNG",
    "selectArea": "Selected area",
    "dragTip": "Tip: start from one corner of the area and drag to the opposite corner.",
    "fast": "Fast",
    "secure": "Secure",
    "free": "Free",
    "mobile": "Mobile Friendly",
    "homeTitle": "ফ্রি অনলাইন টুলস",
    "homeDesc": "Choose PDF tools or image tools. Files stay private in your browser.",
    "pdfCategory": "PDF টুলস",
    "imageCategory": "ইমেজ টুলস",
    "pdfDesc": "Convert images to PDF and merge PDF files securely in your browser.",
    "pdfTitle": "PDF টুলস"
  },
  "ur": {
    "imageToolsTitle": "امیج ٹولز",
    "imageToolsDesc": "Edit, resize, compress and convert images privately in your browser.",
    "open": "ٹول کھولیں",
    "cropTitle": "Crop Image",
    "cropDesc": "Select a rectangular area and crop your image without upload.",
    "resizeTitle": "Resize Image",
    "resizeDesc": "Set exact width and height using input boxes.",
    "compressTitle": "Compress Image",
    "compressDesc": "Reduce image file size while keeping good quality.",
    "convertTitle": "JPG to PNG Converter",
    "convertDesc": "Convert JPG images to PNG directly in your browser.",
    "choose": "Choose Image",
    "noImage": "No image selected",
    "download": "Download",
    "reset": "Reset",
    "preview": "Preview",
    "privacy": "Your image is processed locally in your browser. We do not upload or store your files.",
    "cropHelp": "Click and drag on the image to draw a rectangular crop box. Move your finger or mouse, release, then click download.",
    "downloadCrop": "Download Cropped Image",
    "width": "Width",
    "height": "Height",
    "keepRatio": "Keep aspect ratio",
    "downloadResize": "Download Resized Image",
    "quality": "Quality",
    "downloadCompressed": "Download Compressed Image",
    "originalSize": "Original size",
    "newSize": "Estimated new size",
    "actualNewSize": "Downloaded size",
    "convert": "Convert to PNG",
    "downloadPng": "Download PNG",
    "selectArea": "Selected area",
    "dragTip": "Tip: start from one corner of the area and drag to the opposite corner.",
    "fast": "Fast",
    "secure": "Secure",
    "free": "Free",
    "mobile": "Mobile Friendly",
    "homeTitle": "مفت آن لائن ٹولز",
    "homeDesc": "Choose PDF tools or image tools. Files stay private in your browser.",
    "pdfCategory": "PDF ٹولز",
    "imageCategory": "امیج ٹولز",
    "pdfDesc": "Convert images to PDF and merge PDF files securely in your browser.",
    "pdfTitle": "PDF ٹولز"
  },
  "fa": {
    "imageToolsTitle": "ابزارهای تصویر",
    "imageToolsDesc": "Edit, resize, compress and convert images privately in your browser.",
    "open": "باز کردن ابزار",
    "cropTitle": "Crop Image",
    "cropDesc": "Select a rectangular area and crop your image without upload.",
    "resizeTitle": "Resize Image",
    "resizeDesc": "Set exact width and height using input boxes.",
    "compressTitle": "Compress Image",
    "compressDesc": "Reduce image file size while keeping good quality.",
    "convertTitle": "JPG to PNG Converter",
    "convertDesc": "Convert JPG images to PNG directly in your browser.",
    "choose": "Choose Image",
    "noImage": "No image selected",
    "download": "Download",
    "reset": "Reset",
    "preview": "Preview",
    "privacy": "Your image is processed locally in your browser. We do not upload or store your files.",
    "cropHelp": "Click and drag on the image to draw a rectangular crop box. Move your finger or mouse, release, then click download.",
    "downloadCrop": "Download Cropped Image",
    "width": "Width",
    "height": "Height",
    "keepRatio": "Keep aspect ratio",
    "downloadResize": "Download Resized Image",
    "quality": "Quality",
    "downloadCompressed": "Download Compressed Image",
    "originalSize": "Original size",
    "newSize": "Estimated new size",
    "actualNewSize": "Downloaded size",
    "convert": "Convert to PNG",
    "downloadPng": "Download PNG",
    "selectArea": "Selected area",
    "dragTip": "Tip: start from one corner of the area and drag to the opposite corner.",
    "fast": "Fast",
    "secure": "Secure",
    "free": "Free",
    "mobile": "Mobile Friendly",
    "homeTitle": "ابزارهای آنلاین رایگان",
    "homeDesc": "Choose PDF tools or image tools. Files stay private in your browser.",
    "pdfCategory": "ابزارهای PDF",
    "imageCategory": "ابزارهای تصویر",
    "pdfDesc": "Convert images to PDF and merge PDF files securely in your browser.",
    "pdfTitle": "ابزارهای PDF"
  },
  "ms": {
    "imageToolsTitle": "Alat Imej",
    "imageToolsDesc": "Edit, resize, compress and convert images privately in your browser.",
    "open": "Buka Alat",
    "cropTitle": "Crop Image",
    "cropDesc": "Select a rectangular area and crop your image without upload.",
    "resizeTitle": "Resize Image",
    "resizeDesc": "Set exact width and height using input boxes.",
    "compressTitle": "Compress Image",
    "compressDesc": "Reduce image file size while keeping good quality.",
    "convertTitle": "JPG to PNG Converter",
    "convertDesc": "Convert JPG images to PNG directly in your browser.",
    "choose": "Choose Image",
    "noImage": "No image selected",
    "download": "Download",
    "reset": "Reset",
    "preview": "Preview",
    "privacy": "Your image is processed locally in your browser. We do not upload or store your files.",
    "cropHelp": "Click and drag on the image to draw a rectangular crop box. Move your finger or mouse, release, then click download.",
    "downloadCrop": "Download Cropped Image",
    "width": "Width",
    "height": "Height",
    "keepRatio": "Keep aspect ratio",
    "downloadResize": "Download Resized Image",
    "quality": "Quality",
    "downloadCompressed": "Download Compressed Image",
    "originalSize": "Original size",
    "newSize": "Estimated new size",
    "actualNewSize": "Downloaded size",
    "convert": "Convert to PNG",
    "downloadPng": "Download PNG",
    "selectArea": "Selected area",
    "dragTip": "Tip: start from one corner of the area and drag to the opposite corner.",
    "fast": "Fast",
    "secure": "Secure",
    "free": "Free",
    "mobile": "Mobile Friendly",
    "homeTitle": "Alat Online Percuma",
    "homeDesc": "Choose PDF tools or image tools. Files stay private in your browser.",
    "pdfCategory": "Alat PDF",
    "imageCategory": "Alat Imej",
    "pdfDesc": "Convert images to PDF and merge PDF files securely in your browser.",
    "pdfTitle": "Alat PDF"
  }
};
export function getImageToolText(lang){ return imageToolText[lang] || imageToolText.en; }
